quanto = int (input('quanto você quer somar primeiro?: '))
print('=====================')
print('com quanto?')
maisquanto = int (input(''))
print('=====================')
mais = (quanto + maisquanto)
subtracao = (quanto - maisquanto)
multplicacao = (quanto * maisquanto)
divisao = (quanto / maisquanto)
print('adição = ' , mais)
print('subtração = ' , subtracao)
print('multiplicação = ' , multplicacao)
print('divisão = ' , divisao)
print('=====================')